---
dependencies:
  - { role: shruthirao.java }

galaxy_info:
  author: shruthirao
  description: Tomcat 6 for RHEL/CentOS and Debian/Ubuntu.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.8
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - development
    - web
